### ISSUE TITLE
Partners/Sponsors Update

### ISSUE THREAD

**Issue by ebunayo** [Bloceducare/web3bridgewebsite#108]
Add the remaining partners/sponsors

Base: https://docs.base.org/
Lisk: https://www.figma.com/design/wWFHUoZkrcgeD6lfuXFd5c/Lisk-Logo%2F-Brand-Assets?node-id=0-1&t=u0aiDSZeAEDvgUlN-0
AyaHQ: https://www.ayahq.com/
Web3Ladies: https://drive.google.com/file/d/1-JR3tWI2_vzrC-fI2EL496WcW32WIFQ5/view?usp=sharing
Blockfuse: https://drive.google.com/file/d/1Szdgb6ho5aUQZRXhua1-o42sQg6Z4boT/view?usp=sharing

**Comment by psychemist** [comment]
fixed in PR #120
