### ISSUE TITLE
Refinement of Blockchain Learning Process Order

### ISSUE THREAD

**Issue by Superior212** [Bloceducare/web3bridgewebsite#109]
**Previous Learning Sequence**

Blockchain Security
Ethereum
Solidity
EtherJS & Web3JS
Hardhat
Foundry
Non-Fungible Tokens (NFTs)
Zero Knowledge

**New Proposed Learning Sequence**
Intro to Blockchain
Ethereum
Solidity
EtherJS & Web3JS
Hardhat
Foundry
Non-Fungible Tokens (NFTs)
Zero Knowledge
Blockchain Security

@ebunayo

**Comment by ebunayo** [comment]
> **Previous Learning Sequence**
> 
> Blockchain Security Ethereum Solidity EtherJS & Web3JS Hardhat Foundry Non-Fungible Tokens (NFTs) Zero Knowledge
> 
> **New Proposed Learning Sequence** Intro to Blockchain Ethereum Solidity EtherJS & Web3JS Hardhat Foundry Non-Fungible Tokens (NFTs) Zero Knowledge Blockchain Security
> 
> @ebunayo

Yes, I agree with this. It wasn't meant to follow a particular flow initially but we can re-write the code to come out like this. Expecting a PR. Thanks

**Comment by Superior212** [comment]
PR raised @Goodness5
